### ISSUE TITLE
other special characters seem to fail

### ISSUE THREAD

**Issue by edoderoo** [mediawiki-utilities/python-mwviews#3] opened 2016-02-11 21:10 UTC
Speciaal:Zoeken does work, but 'Speciaal:MyPage/zeusmodepreferences.js' is not working.
This page is showing up in the todaystoplist = p.top_articles('nl.wikipedia' , limit=100) but fails on the p.article_views('nl.wikipedia' ,['Speciaal:MyPage/zeusmodepreferences.js'],start=startday,end=endday)  
on line 99 in article_views.It says KeyError: u'\xe9'

**Comment by milimetric** [comment] 2016-02-11 21:39
Ok, I fixed one small problem that was causing it to not encode '/' and pushed version 0.0.7, but the fact that 'Speciaal:MyPage/zeusmodepreferences.js' is not retrieved is a problem with the pageview API itself. I don't really think that page should've been counted as a pageview in the first place, but maybe I'm wrong.  I've filed this task:  to look into it, but closing this issue because the problem is elsewhere.

Thanks for the report, very useful.

**Closed** 2016-02-20 07:51 UTC

**Comment by milimetric** [comment] 2016-02-23 21:03
This is an interesting issue, but the only remaining problem has to do with
the special case handling of the special page
Speciaal:MyPage/zeusmodepreferences.js.
I don't have time to dig into it now, but I'll keep it in mind.  The
underlying issues of encoding with the API itself have been solved, so all
characters should work now, just pass them into a page title with no
encoding and no replacing of spaces with underscores or anything like
that.  The API will take care of it.
